version: "2"

services:
  mongodb:
    image: mongo:3.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongodb:/data/db"

  rabbitmq:
    image: rabbitmq-custom
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "15674:15674"
      - "5672:5672"
      - "61613:61613"
